encoder:
  _target_: models.encoders.LinearEncoder
  input_dim: ${input_dim} 
  latent_dim: ${latent_dim}
  n_layers: ${n_layers_e}
  activation: ${activation_e}

decoder:
  _target_: models.decoders.LinearDecoder
  output_dim: ${input_dim}
  latent_dim: ${latent_dim}
  n_layers: ${n_layers_d}
  activation: ${activation_d}

autoencoder:
  _target_: models.autoencoders.AE
  encoder: ${encoder}
  decoder: ${decoder}