
batch_size: 32
learning_rate: 1e-3 
    
hydra:
    mode: MULTIRUN
    sweep:
        dir: results/multirun
        subdir: ${hydra.job.override_dirname}
    sweeper:
        params:
          +epochs: 1, 2
          +latent_dim: 5
          