defaults:
    - _self_
    #- override hydra/job_logging: stdout

learning_rate: 1e-3
scheduler_gamma: 0.9

hydra:
    mode: MULTIRUN
    
    sweep:
        dir: results/multirun
        #subdir: ${hydra.job.override_dirname}
        subdir: ${hydra.job.name}
    
    output_subdir: null

    job:
        name: "nvae_logsigma_norm_rel_l2"
        
    

    sweeper:
        params:
          +epochs: 1
          +latent_dim: 5
          +n_layers_e: 3, 4
          +n_layers_d: 3, 4
          +batch_size: 50