
defaults:
    - _self_
    - override hydra/job_logging: stdout


hyper_params:
  - epochs
  - latent_dim
  - batch_size
  - n_layers_e
  - n_layers_d
  - learning_rate
  - scheduler_gamma

  
hydra:
    mode: MULTIRUN
    
    sweep:
        dir: results/multirun
        subdir: ${hydra.job.name}
    
    output_subdir: null

    job:
        name: "nvae_logsigma_norm_rel_l2"


    callbacks:

        save_results: 
            _target_: helper_tools.SaveResultsTable
            tracked_results: 
              - reconstr_loss

        save_best_model:
            _target_: helper_tools.BestModelCallback
            tracked_loss: reconstr_loss
            tracked_model: ae


    sweeper:
        params:
          +epochs: range(1, 8)
          +batch_size: 25, 50, 100
          +latent_dim: range(5, 15)
          +n_layers_e: range(3, 9)
          +n_layers_d: range(3, 9)
          +learning_rate: range(1e-3, 1e-2, step = 5e-3) 
          +scheduler_gamma: 0.9

          