
defaults:
    - _self_
    - override hydra/job_logging: stdout


hydra:
    mode: MULTIRUN
    
    sweep:
        dir: results/multirun
        subdir: ${hydra.job.name}
    
    output_subdir: null

    job:
        name: "baseline_regr"

    callbacks:
        save_results: 
            _target_: helper_tools.SaveResultsCallback

    sweeper:
        params:
          +epochs: 1, 2, 3, 4, 5, 6, 7, 8
          +batch_size: 20, 40, 60, 80, 100
          +regr_lr: 1e-2, 5e-3, 1e-3
          +scheduler_gamma: 0.1, 0.5, 0.9


          