
defaults:
    - _self_
    - override hydra/job_logging: stdout


hydra:
    mode: MULTIRUN
    
    sweep:
        dir: results/multirun
        subdir: ${hydra.job.name}
    
    output_subdir: null

    job:
        name: "joint_ae_regr_norm"

    callbacks:
        save_results: 
            _target_: helper_tools.SaveResultsCallback

    sweeper:
        params:
          +epochs: 1, 2, 3, 4, 5, 6, 7, 8
          +batch_size: 25, 50, 100
          +latent_dim: 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

          +n_layers_e: 3, 4, 5, 6, 7, 8
          +n_layers_d: 3, 4, 5, 6, 7, 8

          +encoder_lr: 1e-2, 5e-3, 1e-3
          +decoder_lr: 1e-2, 5e-3, 1e-3
          +regr_lr: 1e-2, 5e-3, 1e-3
          +scheduler_gamma: 0.9
          
          +ete_regr_weight: 0.5, 0.6, 0.7, 0.8, 0.9

          