
learning_rate: 1e-3 
    
hydra:
    mode: MULTIRUN
    sweep:
        dir: results/multirun
        #subdir: ${hydra.job.override_dirname}
        subdir: ${hydra.job.num}
    sweeper:
        params:
          +epochs: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
          +latent_dim: 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
          +n_layers_e: 3, 4, 5, 6, 7, 8
          +n_layers_d: 3, 4, 5, 6, 7, 8
          +batch_size: 50
          