
defaults:
    - _self_
    - override hydra/job_logging: stdout



hydra:
    mode: MULTIRUN
    
    sweep:
        dir: results/multirun
        #subdir: ${hydra.job.override_dirname}
        subdir: ${hydra.job.name}
    
    output_subdir: null

    job:
        #name: "Test_${hydra.job.id}"
        name: "Test"
    
    callbacks:
        save_results: 
            _target_: helper_tools.SaveResultsCallback

    #job_logging: 

    sweeper:
        params:
          +epochs: 1, 2
          +latent_dim: 5, 10
          +batch_size: 32
          +n_layers_e: 5
          +n_layers_d: 5
          +learning_rate: 1e-3 
          +scheduler_gamma: 0.9
          