
defaults:
    - _self_
    - override hydra/job_logging: stdout


track_params:
  - epochs
  - latent_dim
  - batch_size
  - n_layers_e
  - n_layers_d
  - learning_rate
  - scheduler_gamma


hydra:
    mode: MULTIRUN
    
    sweep:
        dir: results/multirun
        #subdir: ${hydra.job.override_dirname}
        subdir: ${hydra.job.name}
    
    output_subdir: null

    job:
        #name: "Test_${hydra.job.id}"
        name: "Test"
    
    callbacks:
        save_results: 
            _target_: helper_tools.SaveResultsRefactor

    #job_logging: 

    sweeper:
        params:
          #+epochs: 1, 2
          +epochs: range(1, 3)
          +latent_dim: 5
          +batch_size: 32
          +n_layers_e: 5
          +n_layers_d: 5
          +learning_rate: range(1e-3, 1e-2, step = 1e-3) 
          +scheduler_gamma: 0.9
          