
defaults:
    - _self_
    - override hydra/job_logging: stdout

learning_rate: 1e-3 

hydra:
    mode: MULTIRUN
    
    sweep:
        dir: results/multirun
        #subdir: ${hydra.job.override_dirname}
        subdir: ${hydra.job.name}
    
    output_subdir: null

    job:
        #name: "experiment_${hydra.job.id}"
        name: "experiment"
        
    #job_logging: 

    sweeper:
        params:
          +epochs: 1, 2
          +latent_dim: 5, 10
          +n_layers_e: 5
          +n_layers_d: 5
          +batch_size: 32
          