
dataset:
  _target_: data_utils.misc.setup_dataset_build
  kind: ${data_build.dataset_kind}
  normaliser: ${data_build.normaliser}
  exclude_columns: ${data_build.exclude_columns}
  train_size: ${data_build.train_size}